

const baseFont = {
  fontFamily: 'Poppins_400Regular',
};

export const fontConfig = {
  displayLarge: {
    ...baseFont,
    fontFamily: 'PlayfairDisplay_700Bold',
    fontSize: 57,
    letterSpacing: 0,
    lineHeight: 64,
    fontWeight: '700',
  },
  displayMedium: {
    ...baseFont,
    fontFamily: 'PlayfairDisplay_500Medium',
    fontSize: 45,
    letterSpacing: 0,
    lineHeight: 52,
    fontWeight: '500',
  },
  displaySmall: {
    ...baseFont,
    fontFamily: 'PlayfairDisplay_400Regular',
    fontSize: 36,
    letterSpacing: 0,
    lineHeight: 44,
    fontWeight: '400',
  },
  headlineLarge: {
    ...baseFont,
    fontFamily: 'Poppins_700Bold',
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 40,
    fontWeight: '700',
  },
  headlineMedium: {
    ...baseFont,
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 28,
    letterSpacing: 0,
    lineHeight: 36,
    fontWeight: '600',
  },
  headlineSmall: {
    ...baseFont,
    fontFamily: 'Poppins_500Medium',
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 32,
    fontWeight: '500',
  },
  titleLarge: {
    ...baseFont,
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 22,
    letterSpacing: 0,
    lineHeight: 28,
    fontWeight: '600',
  },
  titleMedium: {
    ...baseFont,
    fontFamily: 'Poppins_500Medium',
    fontSize: 16,
    letterSpacing: 0.15,
    lineHeight: 24,
    fontWeight: '500',
  },
  titleSmall: {
    ...baseFont,
    fontFamily: 'Poppins_500Medium',
    fontSize: 14,
    letterSpacing: 0.1,
    lineHeight: 20,
    fontWeight: '500',
  },
  bodyLarge: {
    ...baseFont,
    fontSize: 16,
    letterSpacing: 0.15,
    lineHeight: 24,
    fontWeight: '400',
  },
  bodyMedium: {
    ...baseFont,
    fontSize: 14,
    letterSpacing: 0.25,
    lineHeight: 20,
    fontWeight: '400',
  },
  bodySmall: {
    ...baseFont,
    fontSize: 12,
    letterSpacing: 0.4,
    lineHeight: 16,
    fontWeight: '400',
  },
  labelLarge: {
    ...baseFont,
    fontFamily: 'Poppins_500Medium',
    fontSize: 14,
    letterSpacing: 0.1,
    lineHeight: 20,
    fontWeight: '500',
  },
  labelMedium: {
    ...baseFont,
    fontFamily: 'Poppins_500Medium',
    fontSize: 12,
    letterSpacing: 0.5,
    lineHeight: 16,
    fontWeight: '500',
  },
  labelSmall: {
    ...baseFont,
    fontFamily: 'Poppins_500Medium',
    fontSize: 11,
    letterSpacing: 0.5,
    lineHeight: 16,
    fontWeight: '500',
  },
};